### ISSUE TITLE
dbt run & dbt test Encountered an error

### ISSUE THREAD

**Issue by hengaini2055** [Data-Engineer-Camp/dbt-dimensional-modelling#3]
(pandas20) E:\temp\panel_mini\dbt-dimensional-modelling-main\adventureworks>dbt run
03:23:18  Running with dbt=1.5.1
03:23:19  Found 8 models, 42 tests, 0 snapshots, 0 analyses, 426 macros, 0 operations, 15 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
03:23:19
03:23:19
03:23:19  Finished running  in 0 hours 0 minutes and 0.02 seconds (0.02s).
03:23:19  Encountered an error:
Runtime Error

**Comment by jonathanneo** [comment]
Hi @hengaini2055 , are there more logs after the `Runtime error`? 

To help troubleshoot, could you please provide: 
- Details of your Operating System (Windows, MacOS, Linux)? 
- What database are you using (PostgreSQL 14.0, DuckDB 0.7.1, etc)?
